<?php


namespace App\Helpers\General;

class Tables
{
    const TABLE_NAMES = [
        'users' => 'users',
        'roles' => 'roles',
        'model_has_roles' => 'model_has_roles',
        'permissions' => 'permissions',
        'break_lists' => 'break_lists',
        'pause_codes' => 'pause_codes',
        'ctc_api_keys' => 'click_to_call_api',
        'area_wise_caller_ids' => 'area_wise_caller_ids',
        'area_wise_caller_id_lists' => 'area_wise_caller_id_lists',
        'call_queues' => 'call_queues',
        'call_queue_agents' => 'call_queue_agents',
        'do_not_call_lists' => 'dnc_lists',
        'forwarding_groups' => 'forwarding_groups',
        'forwarding_group_destinations' => 'forwarding_group_destinations',
        'do_not_call_numbers' => 'dnc_numbers',
        'numbers' => 'tfn_numbers',
        'endpoints' => 'ps_endpoints',
        'queues' => 'pbx_queues',
        'queue_rules' => 'pbx_queue_rules',
        'queue_members' => 'pbx_queue_members',
        'queue_stats' => 'pbx_queue_stats',
        'voicemail' => 'voicemail',
        'conferences' => 'conference',
        'music_on_hold' => 'pbx_music_on_hold',
        'sip_servers' => 'sip_servers',
        'user_access' => 'user_access',
        'sites' => 'sites',
        'departments' => 'departments',
        'time_conditions' => 'time_conditions',
        'business_hours' => 'business_hours',
        'caller_ids' => 'caller_ids',
        'sip-proxies' => 'sip-proxies',
        'switch_clients' => 'switch_clients',
        'quick_transfer_lists' => 'quick_transfer_lists',
        'quick_transfer_numbers' => 'quick_transfer_numbers',
        'recordings' => 'recordings',
        'text_to_speech' => 'text_to_speech',
        'list_mix' => 'list_mix',
        'list_mix_composition' => 'list_mix_composition',
        'virtual_receptionists' => 'virtual_receptionists',
        'virtual_receptionists_menu' => 'virtual_receptionists_menu',
        'notifications' => 'notifications',
        'sms_vendors' => 'sms_vendors',
        'agent_scripts' => 'agent_scripts',
        'alerts' => 'alerts',
        'server_maintenance' => 'server_maintenance',
        'lead_lists' => 'lead_lists',
        'leads' => 'leads',
        'sms_email_templates' =>'sms_email_templates',
        'modules' => 'modules',
    ];
}
